### ISSUE TITLE
a couple of comments

### ISSUE THREAD

**Issue by Bamieh** [lucasfs7/google-maps-infobox-module#1]
The function InfoBox.prototype.getCloseBoxImg_ on line 244 infobox-module.js
i believe using one string to build the img variable instead of doing 7 concatenations is lighter.
and i dont understand why some variables are set to null, why not just keep them undefined?
Thanks

**Comment by bewards** [comment]
@Bamieh, the infobox-module script is a copy of the infobox plugin, so there's nothing in there that should be changed.

**Comment by lucasfs7** [comment]
this concerns to the plugin itself not to this modules, which is a wrapper for the plugin
