### ISSUE TITLE
Error google is not defined

### ISSUE THREAD

**Issue by akavolkol** [lucasfs7/google-maps-infobox-module#11]
An issue occurs when transpiling dependency with webpack. 
```
InfoBox.prototype = new google.maps.OverlayView();
                        ^
ReferenceError: google is not defined
```
suggest to make a reference to window.google in package scope

**Comment by jamesmosier** [comment]
How did you resolve this issue @akavolkol ?

**Comment by akavolkol** [comment]
@jamesmosier I have included it only when it needed (on a client side). `const infoBox = new (require('google-maps-infobox').InfoBox)()`
